@SETLOCAL
@IF NOT DEFINED NODE_PATH (
  @SET "NODE_PATH=C:\Users\Lenovo\Desktop\pathable\PathAble\PathAble\node_modules\.pnpm\vite@7.3.2_@types+node@25.3_d5269a53d302b42e602832b0eaecec0c\node_modules\vite\node_modules;C:\Users\Lenovo\Desktop\pathable\PathAble\PathAble\node_modules\.pnpm\vite@7.3.2_@types+node@25.3_d5269a53d302b42e602832b0eaecec0c\node_modules;C:\Users\Lenovo\Desktop\pathable\PathAble\PathAble\node_modules\.pnpm\node_modules"
) ELSE (
  @SET "NODE_PATH=C:\Users\Lenovo\Desktop\pathable\PathAble\PathAble\node_modules\.pnpm\vite@7.3.2_@types+node@25.3_d5269a53d302b42e602832b0eaecec0c\node_modules\vite\node_modules;C:\Users\Lenovo\Desktop\pathable\PathAble\PathAble\node_modules\.pnpm\vite@7.3.2_@types+node@25.3_d5269a53d302b42e602832b0eaecec0c\node_modules;C:\Users\Lenovo\Desktop\pathable\PathAble\PathAble\node_modules\.pnpm\node_modules;%NODE_PATH%"
)
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\vite\bin\vite.js" %*
) ELSE (
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\vite\bin\vite.js" %*
)
